In [1]:
# Importing necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
# importing dataset
dataset = pd.read_csv("CKD.csv")
dataset.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.0,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.0,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.0,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.0,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.0,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes


In [3]:
# Categorical data handling
dataset = pd.get_dummies(dataset,drop_first=True,dtype=int)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1


In [4]:
# Dataset columns
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [5]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [6]:
# Feature and target selection
independent = dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dependent = dataset['classification_yes']

In [7]:
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1


In [8]:
dependent

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: int64

In [9]:
# Splitting data into training and testing sets
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size=0.25,random_state=0)

In [10]:
x_train.shape

(299, 27)

In [11]:
x_test.shape

(100, 27)

In [12]:
y_train.shape

(299,)

In [13]:
y_test.shape

(100,)

In [14]:
# Data standardization
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [16]:
# GridSearch CV
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

# Defining the different parameters for gridsearch optimization
param_grid = {'criterion':['gini','entropy','log_loss'],
              'n_estimators':[10,25,50,75,100],
              'class_weight':['balanced','balanced_subsample'],
              'max_features':['sqrt','log2']}


grid = GridSearchCV(RandomForestClassifier(),param_grid,refit=True,verbose=3,scoring='f1_weighted',n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 60 candidates, totalling 300 fits


GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'class_weight': ['balanced', 'balanced_subsample'],
                         'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 25, 50, 75, 100]},
             scoring='f1_weighted', verbose=3)

In [17]:
# Best gridseach parameter
grid.best_params_

{'class_weight': 'balanced',
 'criterion': 'log_loss',
 'max_features': 'sqrt',
 'n_estimators': 50}

In [18]:
# Model prediction
y_pred = grid.predict(x_test)
y_pred

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1])

In [19]:
# Evaluation metrics
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[35  1]
 [ 0 64]]


In [20]:
# Classification report
from sklearn.metrics import classification_report
report = classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       1.00      0.97      0.99        36
           1       0.98      1.00      0.99        64

    accuracy                           0.99       100
   macro avg       0.99      0.99      0.99       100
weighted avg       0.99      0.99      0.99       100



In [21]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

np.float64(1.0)

In [22]:
# Grid results
table = pd.DataFrame(grid.cv_results_)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_class_weight,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.032158,0.001568,0.006389,0.001097,balanced,gini,sqrt,10,"{'class_weight': 'balanced', 'criterion': 'gin...",0.966898,0.983259,0.966898,0.983259,1.000000,0.980063,0.012366,32
1,0.071411,0.008242,0.008896,0.001882,balanced,gini,sqrt,25,"{'class_weight': 'balanced', 'criterion': 'gin...",0.983396,0.983259,0.983396,0.983259,1.000000,0.986662,0.006669,3
2,0.106815,0.004806,0.007252,0.000743,balanced,gini,sqrt,50,"{'class_weight': 'balanced', 'criterion': 'gin...",0.983396,0.983259,0.966898,0.966667,1.000000,0.980044,0.012422,33
3,0.142589,0.004371,0.009536,0.000833,balanced,gini,sqrt,75,"{'class_weight': 'balanced', 'criterion': 'gin...",0.983396,0.983259,0.983396,0.983259,1.000000,0.986662,0.006669,3
4,0.197976,0.013470,0.012922,0.002107,balanced,gini,sqrt,100,"{'class_weight': 'balanced', 'criterion': 'gin...",0.983396,0.983259,0.983396,0.966667,0.982967,0.979937,0.006637,38
5,0.022374,0.001453,0.004048,0.000328,balanced,gini,log2,10,"{'class_weight': 'balanced', 'criterion': 'gin...",0.983396,0.983259,0.983396,0.983259,0.983123,0.983287,0.000102,23
6,0.055338,0.005250,0.004862,0.000103,balanced,gini,log2,25,"{'class_weight': 'balanced', 'criterion': 'gin...",0.983396,0.983259,0.983396,0.983259,1.000000,0.986662,0.006669,3
7,0.098919,0.008658,0.007388,0.001380,balanced,gini,log2,50,"{'class_weight': 'balanced', 'criterion': 'gin...",0.983396,0.983259,1.000000,0.966667,0.982967,0.983258,0.010542,26
8,0.165785,0.007421,0.010072,0.001198,balanced,gini,log2,75,"{'class_weight': 'balanced', 'criterion': 'gin...",0.983396,0.983259,0.983396,0.966667,0.982967,0.979937,0.006637,38
9,0.209835,0.005480,0.011514,0.000894,balanced,gini,log2,100,"{'class_weight': 'balanced', 'criterion': 'gin...",0.983396,0.983259,0.983396,0.983259,1.000000,0.986662,0.006669,3


In [23]:
age_input=float(input("Enter age:"))
bp_input= float(input("Enter bp:"))
al_input=float(input("Enter al:"))
su_input=float(input("Enter su:"))
bgr_input=float(input("Enter bgr:"))
bu_input=float(input("Enter bu:"))
sc_input=float(input("Enter sc:"))
sod_input=float(input("Enter sod:"))
pot_input=float(input("Enter pot:")) 
hrmo_input=float(input("Enter hrmo:"))
pcv_input=float(input("Enter pcv:"))
wc_input=float(input("Enter wc:"))  
rc_input=float(input("Enter rc:"))  
sg_b_input=float(input("Enter sg_b:"))  
sg_c_input=float(input("Enter sg_c:"))  
sg_d_input=float(input("Enter sg_d:"))  
sg_e_input=float(input("Enter sg_e:"))  
rbc_normal_input=float(input("Enter rbc_normal:"))  
pc_normal_input=float(input("Enter pc_normal:")) 
pcc_present_input=float(input("Enter pcc_present:"))  
ba_present_input=float(input("Enter ba_present:"))  
htn_yes_input=float(input("Enter htn_yes:"))  
dm_yes_input=float(input("Enter dm_yes:"))  
cad_yes_input=float(input("Enter cad_yes:"))  
appet_yes_input=float(input("Enter appet_yes:"))  
pe_yes_input=float(input("Enter pe_yes:")) 
ane_yes_input=float(input("Enter ane_yes:")) 

In [24]:
scaled_input = sc.transform([[age_input,bgr_input,al_input,su_input,bgr_input,bu_input,
                              sc_input,sod_input,pot_input,hrmo_input,pcv_input,wc_input,
                              rc_input,sg_b_input,sg_c_input,sg_d_input,sg_e_input,rbc_normal_input,
                              pc_normal_input,pcc_present_input,ba_present_input,htn_yes_input,
                              dm_yes_input,cad_yes_input,appet_yes_input,pe_yes_input,ane_yes_input]])

C:\Users\thiru\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [25]:
result = grid.predict(scaled_input)
result

array([0])